"""add payment gateway fields

Revision ID: c2a60e9fdaf9
Revises: a227aed64be5
Create Date: 2026-09-05 23:14:21.315829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a60e9fdaf9'
down_revision: Union[str, None] = 'a227aed64be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_placeholders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway', sa.String(length=30), nullable=False, server_default='mock'))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False, server_default='NGN'))
        batch_op.add_column(sa.Column('checkout_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_payment_placeholders_gateway_reference', ['gateway_reference'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_placeholders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_placeholders_gateway_reference', type_='unique')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('checkout_url')
        batch_op.drop_column('currency')
        batch_op.drop_column('amount')
        batch_op.drop_column('gateway')

    # ### end Alembic commands ###
